"use strict";
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
const clamp=(value,min,max)=>Math.min(max,Math.max(min,+value||0));
const signed=value=>`${value>=0?"+":""}${value}`;
const mod=score=>Math.floor((score-10)/2);
const safeImage=value=>/^data:image\/(?:png|jpeg|webp);base64,/i.test(value||"")?value:"";
const fileName=value=>(value||"未命名角色").replace(/[\\/:*?"<>|]/g,"-");
let selectedId=new URLSearchParams(location.search).get("id")||CharacterStore.list()[0]?.id||"";
let activeTab="play";

function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),1900);}
function download(name,content){const blob=new Blob([content],{type:"application/json;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function schoolById(id){return SCHOOLS.find(school=>school.id===id);}
function record(){return CharacterStore.get(selectedId);}
function token(build,className="manager-token"){const image=safeImage(build.tokenImage);return `<div class="${className}">${image?`<img src="${image}" alt="${esc(build.name)}的角色形象">`:"✦"}</div>`;}
function mutate(mutator,logText=""){const updated=CharacterStore.update(selectedId,mutator,logText);if(updated)render();}
function formatTime(value){try{return new Intl.DateTimeFormat("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value));}catch{return "";}}

function renderRoster(){
  const characters=CharacterStore.list();$("#rosterCount").textContent=characters.length;
  $("#characterRoster").innerHTML=characters.map(character=>{const build=character.build,school=schoolById(build.schoolId);return `<button class="roster-card ${character.id===selectedId?"active":""}" data-action="selectCharacter" data-id="${character.id}">${token(build,"roster-token")}<span class="roster-copy"><b>${esc(character.name)}</b><small>${esc(school?.name||"未选学派")} · HP ${character.play.currentHp}/${character.play.maxHp}</small></span><span class="roster-op">${build.totalOP} OP</span></button>`;}).join("");
}
function emptyArchive(){return `<div class="empty-archive"><div><div class="empty-sigil"><span>◇</span></div><h2>还没有人物档案</h2><p>完成一次车卡后，角色会出现在这里。你可以持续记录生命、资源和背包，并在获得新的 OP 后继续升级原角色。</p><button class="primary-button" data-action="newCharacter">创建第一个角色</button></div></div>`;}
function tabs(){return `<nav class="manager-tabs" aria-label="人物卡页面"><button class="manager-tab ${activeTab==="play"?"active":""}" data-action="tab" data-value="play">游玩状态</button><button class="manager-tab ${activeTab==="inventory"?"active":""}" data-action="tab" data-value="inventory">背包与财物</button><button class="manager-tab ${activeTab==="sheet"?"active":""}" data-action="tab" data-value="sheet">能力与记录</button></nav>`;}
function characterHeader(character){const build=character.build,school=schoolById(build.schoolId);return `<header class="character-head">${token(build)}<div class="character-head-copy"><span class="eyebrow">${build.totalOP} OP CHARACTER</span><h2>${esc(character.name)}</h2><p>${esc(build.concept||"尚未填写角色概念")} · ${esc(school?.name||build.derived?.initialSchool||"未选学派")}</p></div><div class="character-head-actions"><button class="primary-button" data-action="upgrade">继续升级</button><button class="ghost-button" data-action="exportCharacter">导出此角色</button><button class="ghost-button danger-button" data-action="deleteCharacter" aria-label="删除角色">删除</button></div></header>${tabs()}`;}
function saveDots(type,count){return `<div class="dot-track">${[1,2,3].map(index=>`<button class="save-dot ${type} ${count>=index?"on":""}" data-action="deathSave" data-type="${type}" data-value="${index}" aria-label="${type==="success"?"成功":"失败"} ${index}"></button>`).join("")}</div>`;}
function resourceRows(play){return play.resources.length?play.resources.map(resource=>`<div class="resource-row"><button class="resource-name resource-edit" data-action="editResource" data-id="${resource.id}" title="修改名称与上限"><b>${esc(resource.name)}</b><small>${esc(resource.notes||({short:"短休恢复",long:"长休恢复",none:"手动恢复"}[resource.recharge]))}</small></button><button class="counter-button" data-action="resourceDelta" data-id="${resource.id}" data-value="-1">−</button><div class="resource-count">${resource.current}<small> / ${resource.max}</small></div><button class="counter-button" data-action="resourceDelta" data-id="${resource.id}" data-value="1">＋</button><button class="resource-delete" data-action="deleteResource" data-id="${resource.id}" aria-label="删除资源">×</button></div>`).join(""):`<div class="empty">尚未添加自定义资源。</div>`;}
function playView(character){
  const {play,build}=character,derived=build.derived||{},stats=derived.finalStats||{};
  return `<div class="manager-grid">
    <section class="manager-card"><div class="manager-card-head"><div><h3>生命状态</h3><small>受到伤害与获得治疗时直接调整</small></div></div><div class="hp-display"><div class="hp-number"><input type="number" min="0" max="${play.maxHp}" value="${play.currentHp}" data-field="currentHp" aria-label="当前生命值"><small>当前 HP</small></div><div class="hp-divider">/</div><div class="hp-max">${play.maxHp}<small>生命上限</small></div></div><form id="hpDeltaForm" class="hp-delta-form"><label for="hpDeltaInput">生命变化</label><div><input id="hpDeltaInput" name="delta" type="text" inputmode="numeric" autocomplete="off" placeholder="例如 -6 或 +2" aria-describedby="hpDeltaHint" required><button class="primary-button" type="submit">应用</button></div><small id="hpDeltaHint">负数表示受到伤害，正数表示恢复生命；按回车也可应用。</small></form><div class="temp-hp"><label for="tempHp">临时生命值</label><input id="tempHp" type="number" min="0" value="${play.tempHp}" data-field="tempHp"></div></section>
    <section class="manager-card"><div class="manager-card-head"><div><h3>战斗核心</h3><small>从车卡数据自动计算</small></div><div class="choice-row"><button class="ghost-button" data-action="shortRest">短休</button><button class="ghost-button" data-action="longRest">长休</button></div></div><div class="play-core-grid"><div><b>${derived.ac??"—"}</b><small>AC</small></div><div><b>${signed(derived.initiative||0)}</b><small>先攻</small></div><div><b>${signed(derived.proficiency||2)}</b><small>熟练</small></div><div><b>${play.hitDice}/${play.maxHitDice}</b><small>生命骰</small></div></div><div class="save-track"><div class="save-box"><small>死亡豁免成功</small>${saveDots("success",play.deathSuccess)}</div><div class="save-box"><small>死亡豁免失败</small>${saveDots("failure",play.deathFailure)}</div></div><div class="exhaustion-row"><span>力竭等级</span><div class="stepper"><button class="counter-button" data-action="exhaustion" data-value="-1">−</button><b>${play.exhaustion}</b><button class="counter-button" data-action="exhaustion" data-value="1">＋</button></div></div></section>
    <section class="manager-card wide"><div class="manager-card-head"><div><h3>资源计数</h3><small>可自行添加 AP、契约位、仪式次数、消耗品次数等资源</small></div></div><div class="resource-list">${resourceRows(play)}</div><form id="resourceForm" class="resource-form"><input name="name" required maxlength="30" placeholder="资源名称，如 AP"><input name="max" type="number" required min="1" value="1" aria-label="资源上限"><select name="recharge" aria-label="恢复方式"><option value="none">手动恢复</option><option value="short">短休恢复</option><option value="long">长休恢复</option></select><button class="ghost-button" type="submit">添加资源</button></form></section>
    <section class="manager-card wide"><div class="manager-card-head"><div><h3>当前状态</h3><small>记录中毒、目盲、专注或场景自定义状态</small></div></div><div class="condition-list">${play.conditions.length?play.conditions.map((condition,index)=>`<span class="condition-chip">${esc(condition)}<button data-action="removeCondition" data-value="${index}" aria-label="移除${esc(condition)}">×</button></span>`).join(""):'<span class="preview-subtitle">目前没有记录状态。</span>'}</div><form id="conditionForm" class="inline-form"><input name="condition" required maxlength="24" placeholder="输入状态名称"><button class="ghost-button" type="submit">添加状态</button></form></section>
  </div>`;
}
function inventoryView(character){const {play}=character,totalWeight=play.inventory.reduce((sum,item)=>sum+(+item.qty||0)*(+item.weight||0),0);return `<div class="manager-grid">
  <section class="manager-card wide"><div class="manager-card-head"><div><h3>货币与资金</h3><small>字段名称沿用规则中的起始资金口径</small></div></div><div class="currency-grid"><label>纸币／通货<input type="number" min="0" value="${play.currency.money}" data-currency="money"></label><label>金币<input type="number" min="0" value="${play.currency.gold}" data-currency="gold"></label><label>银币<input type="number" min="0" value="${play.currency.silver}" data-currency="silver"></label><label>铜币<input type="number" min="0" value="${play.currency.copper}" data-currency="copper"></label></div></section>
  <section class="manager-card wide"><div class="manager-card-head"><div><h3>背包物品</h3><small>装备、消耗品与任务道具统一管理</small></div><div class="inventory-summary"><span>${play.inventory.length} 类物品</span><span>总负重 ${Math.round(totalWeight*100)/100}</span></div></div><div class="inventory-list">${play.inventory.length?play.inventory.map(item=>`<div class="inventory-row"><button class="equip-toggle ${item.equipped?"on":""}" data-action="toggleEquip" data-id="${item.id}" title="装备／卸下">◆</button><div class="item-name"><b>${esc(item.name)}</b><small>${item.equipped?"已装备":"背包中"}</small></div><button class="counter-button" data-action="itemDelta" data-id="${item.id}" data-value="-1">−</button><b>${item.qty}</b><button class="counter-button" data-action="itemDelta" data-id="${item.id}" data-value="1">＋</button><span class="item-weight">${item.weight||0} 重</span><span class="item-note">${esc(item.notes||"")}</span><button class="resource-delete" data-action="deleteItem" data-id="${item.id}" aria-label="删除物品">×</button></div>`).join(""):'<div class="empty">背包还是空的。</div>'}</div><form id="inventoryForm" class="inventory-form"><input name="name" required maxlength="50" placeholder="物品名称"><input name="qty" type="number" min="1" value="1" aria-label="数量"><input name="weight" type="number" min="0" step="0.1" value="0" aria-label="单件负重"><input name="notes" maxlength="80" placeholder="备注（可选）"><button class="ghost-button" type="submit">加入背包</button></form></section></div>`;}
function nodeList(build){return (build.schoolOrder||[]).flatMap(schoolId=>{const school=schoolById(schoolId);return (build.schoolNodes?.[schoolId]||[]).map(nodeId=>{const node=school?.nodes.find(entry=>entry.id===nodeId);return node?`<div class="manager-node"><span>${esc(school.name)} · ${esc(node.id)}</span><b>${esc(node.name)}</b><small>${node.cost} OP · ${esc(node.summary||"")}</small></div>`:"";});}).join("");}
function sheetView(character){const {build,play}=character,derived=build.derived||{},stats=derived.finalStats||{},skills=Object.entries(derived.skills||{}).filter(([name])=>(build.backgroundSkills||[]).includes(name)||(build.schoolSkills||[]).includes(name));return `<div class="manager-grid">
  <section class="manager-card wide"><div class="manager-card-head"><div><h3>六项属性</h3><small>升级后会从车卡工具同步</small></div></div><div class="sheet-attribute-grid">${ATTRIBUTES.map(attr=>`<div><span>${attr}</span><b>${stats[attr]??build.stats?.[attr]??8}</b><small>${signed(mod(stats[attr]??build.stats?.[attr]??8))}</small></div>`).join("")}</div></section>
  <section class="manager-card"><div class="manager-card-head"><div><h3>熟练技能</h3><small>仅列出具有熟练的技能</small></div></div><div class="manager-pill-list">${skills.length?skills.map(([name,value])=>`<span>${name} ${signed(value)}</span>`).join(""):'<span>尚未记录</span>'}</div></section>
  <section class="manager-card"><div class="manager-card-head"><div><h3>角色摘要</h3><small>车卡完成时的核心选择</small></div></div><div class="preview-line"><span>初始学派</span><b>${esc(derived.initialSchool||"—")}</b></div><div class="preview-line"><span>主学派</span><b>${esc(derived.mainSchool||"—")}</b></div><div class="preview-line"><span>总 OP</span><b>${build.totalOP}</b></div><div class="preview-line"><span>背景</span><b>${esc((BACKGROUNDS.find(bg=>bg.id===build.backgroundId)?.name)||build.customBackground?.name||"—")}</b></div><div class="preview-line"><span>武器</span><b>${esc(build.weapon||"—")}</b></div><div class="preview-line"><span>护甲</span><b>${esc(ARMORS.find(armor=>armor.id===build.armor)?.name||"无护甲")}</b></div></section>
  <section class="manager-card wide"><div class="manager-card-head"><div><h3>学派节点</h3><small>点击“继续升级”可回到节点树增加 OP 与兼修</small></div></div><div class="manager-node-list">${nodeList(build)||'<div class="empty">尚未点亮节点。</div>'}</div></section>
  <section class="manager-card"><div class="manager-card-head"><div><h3>长期笔记</h3><small>可记录人物关系、任务线索与长期状态</small></div></div><textarea class="manager-notes" data-field="notes" placeholder="写下这名角色需要长期保留的信息……">${esc(play.notes)}</textarea></section>
  <section class="manager-card"><div class="manager-card-head"><div><h3>近期记录</h3><small>保留最近 40 条关键变化</small></div></div><div class="log-list">${play.sessionLog.length?play.sessionLog.slice(0,12).map(entry=>`<div class="log-row"><b>${esc(entry.text)}</b><small>${formatTime(entry.at)}</small></div>`).join(""):'<div class="empty">暂无记录。</div>'}</div></section>
  </div>`;}
function render(){
  const characters=CharacterStore.list();if(selectedId&&!characters.some(character=>character.id===selectedId))selectedId=characters[0]?.id||"";renderRoster();
  const character=record();$("#managerContent").innerHTML=character?characterHeader(character)+(activeTab==="play"?playView(character):activeTab==="inventory"?inventoryView(character):sheetView(character)):emptyArchive();
  try{if(character)history.replaceState(null,"",`manager.html?id=${encodeURIComponent(character.id)}`);else history.replaceState(null,"","manager.html");}catch{}
}

document.addEventListener("click",event=>{
  const button=event.target.closest("[data-action]");if(!button)return;const action=button.dataset.action,value=button.dataset.value,itemId=button.dataset.id;
  if(action==="selectCharacter"){selectedId=itemId;render();return;}
  if(action==="tab"){activeTab=value;render();return;}
  if(action==="newCharacter"){CharacterStore.newDraft();location.href="index.html";return;}
  if(action==="importLibrary"){$("#libraryImport").click();return;}
  if(action==="exportLibrary"){download(`全部人物档案-${new Date().toISOString().slice(0,10)}.json`,CharacterStore.exportLibrary());toast("全部人物档案已导出");return;}
  const character=record();if(!character)return;
  if(action==="upgrade"){const current=+character.build.totalOP||1,next=prompt(`输入升级后的总 OP（当前 ${current}）：`,String(Math.min(30,current+1)));if(next===null)return;const total=+next;if(!Number.isInteger(total)||total<current||total>30){toast("请输入不低于当前值、且不超过 30 的整数 OP");return;}CharacterStore.beginUpgrade(selectedId,total);location.href="index.html";return;}
  if(action==="exportCharacter"){download(`${fileName(character.name)}-完整人物档案.json`,JSON.stringify({version:1,characters:[character]},null,2));toast("人物档案已导出");return;}
  if(action==="deleteCharacter"){if(confirm(`确定删除“${character.name}”吗？请先导出备份，删除后无法恢复。`)){CharacterStore.remove(selectedId);selectedId="";render();toast("人物档案已删除");}return;}
  if(action==="deathSave"){const key=button.dataset.type==="success"?"deathSuccess":"deathFailure",count=+value;mutate(play=>{play[key]=play[key]===count?count-1:count;});return;}
  if(action==="exhaustion"){mutate(play=>{play.exhaustion=clamp(play.exhaustion+(+value),0,6);},"调整力竭等级");return;}
  if(action==="shortRest"){mutate(play=>{play.resources.forEach(resource=>{if(resource.recharge==="short")resource.current=resource.max;});},"完成短休并恢复短休资源");return;}
  if(action==="longRest"){mutate(play=>{play.currentHp=play.maxHp;play.tempHp=0;play.deathSuccess=0;play.deathFailure=0;play.exhaustion=Math.max(0,play.exhaustion-1);play.hitDice=Math.min(play.maxHitDice,play.hitDice+Math.max(1,Math.ceil(play.maxHitDice/2)));play.resources.forEach(resource=>{if(["short","long"].includes(resource.recharge))resource.current=resource.max;if(resource.name==="生命骰")resource.current=play.hitDice;});},"完成长休并恢复生命与资源");return;}
  if(action==="resourceDelta"){mutate(play=>{const resource=play.resources.find(entry=>entry.id===itemId);if(resource){resource.current=clamp(resource.current+(+value),0,resource.max);if(resource.name==="生命骰")play.hitDice=resource.current;}});return;}
  if(action==="editResource"){const resource=character.play.resources.find(entry=>entry.id===itemId);if(!resource)return;const name=prompt("资源名称：",resource.name);if(name===null||!name.trim())return;const maxText=prompt("资源上限：",String(resource.max));if(maxText===null)return;const maximum=Math.floor(+maxText);if(!Number.isInteger(maximum)||maximum<1){toast("资源上限必须是正整数");return;}mutate(play=>{const target=play.resources.find(entry=>entry.id===itemId);if(target){target.name=name.trim();target.max=maximum;target.current=Math.min(target.current,maximum);}});return;}
  if(action==="deleteResource"){mutate(play=>{play.resources=play.resources.filter(resource=>resource.id!==itemId);});return;}
  if(action==="removeCondition"){mutate(play=>{play.conditions.splice(+value,1);},"移除状态");return;}
  if(action==="toggleEquip"){mutate(play=>{const item=play.inventory.find(entry=>entry.id===itemId);if(item)item.equipped=!item.equipped;});return;}
  if(action==="itemDelta"){mutate(play=>{const item=play.inventory.find(entry=>entry.id===itemId);if(item)item.qty=Math.max(0,item.qty+(+value));});return;}
  if(action==="deleteItem"){mutate(play=>{play.inventory=play.inventory.filter(item=>item.id!==itemId);},"移除背包物品");return;}
});
document.addEventListener("submit",event=>{
  event.preventDefault();const form=event.target,data=new FormData(form);
  if(form.id==="hpDeltaForm"){const raw=String(data.get("delta")||"").trim();if(!/^[+-]?\d+$/.test(raw)){toast("请输入整数，例如 -6 或 +2");return;}const delta=Number(raw);if(delta===0){toast("生命变化不能为 0");return;}mutate(play=>{play.currentHp=clamp(play.currentHp+delta,0,play.maxHp);},delta<0?`受到 ${Math.abs(delta)} 点伤害`:`恢复 ${delta} 点生命`);return;}
  if(form.id==="resourceForm"){const name=String(data.get("name")||"").trim(),max=Math.max(1,+data.get("max")||1),recharge=String(data.get("recharge")||"none");if(!name)return;mutate(play=>{play.resources.push({id:CharacterStore.id(),name,current:max,max,recharge,notes:""});},`添加资源：${name}`);return;}
  if(form.id==="conditionForm"){const condition=String(data.get("condition")||"").trim();if(!condition)return;mutate(play=>{if(!play.conditions.includes(condition))play.conditions.push(condition);},`添加状态：${condition}`);return;}
  if(form.id==="inventoryForm"){const name=String(data.get("name")||"").trim();if(!name)return;const qty=Math.max(1,+data.get("qty")||1),weight=Math.max(0,+data.get("weight")||0),notes=String(data.get("notes")||"").trim();mutate(play=>{play.inventory.push({id:CharacterStore.id(),name,qty,weight,equipped:false,notes});},`获得物品：${name} ×${qty}`);}
});
document.addEventListener("change",event=>{
  const input=event.target;if(input.id==="libraryImport"&&input.files[0]){const reader=new FileReader();reader.onload=()=>{try{CharacterStore.importPayload(reader.result);selectedId=CharacterStore.list()[0]?.id||"";render();toast("人物档案已读取");}catch{toast("无法读取这个备份文件");}};reader.readAsText(input.files[0]);return;}
  if(input.dataset.field){const key=input.dataset.field,value=key==="notes"?input.value:+input.value;mutate(play=>{play[key]=value;});return;}
  if(input.dataset.currency){const key=input.dataset.currency;mutate(play=>{play.currency[key]=Math.max(0,+input.value||0);});}
});
render();
